export const FILTERS = [
    { name: 'Original', style: { filter: 'none' } },
    { name: 'Warm', style: { filter: 'sepia(0.3) saturate(1.2)' } },
    { name: 'Cool', style: { filter: 'hue-rotate(-30deg) saturate(0.9) brightness(1.05)' } },
    { name: 'Vivid', style: { filter: 'saturate(1.6) contrast(1.1)' } },
    { name: 'B&W', style: { filter: 'grayscale(100%) contrast(1.1)' } },
    { name: 'Soft', style: { filter: 'contrast(0.9) brightness(1.05) saturate(0.9)' } },
    { name: 'Contrast', style: { filter: 'contrast(1.4)' } },
    { name: 'Fade', style: { filter: 'brightness(1.1) contrast(0.85) saturate(0.8)' } },
    { name: 'Film', style: { filter: 'sepia(0.2) contrast(1.1) saturate(1.2) brightness(0.95)' } },
    { name: 'Bright', style: { filter: 'brightness(1.2) saturate(1.1)' } },
    { name: 'Mono', style: { filter: 'grayscale(100%) brightness(0.9) contrast(1.2)' } },
    { name: 'Noir', style: { filter: 'grayscale(100%) contrast(1.5) brightness(0.8)' } },
    { name: 'Dramatic', style: { filter: 'contrast(1.4) saturate(1.2) sepia(0.1)' } },
    { name: 'Sepia', style: { filter: 'sepia(0.8) contrast(1.1)' } },
    { name: 'Vintage', style: { filter: 'sepia(0.4) saturate(1.4) contrast(0.9) brightness(0.9)' } },
    { name: 'Matte', style: { filter: 'contrast(0.85) brightness(1.1) saturate(0.5)' } },
    { name: 'Golden', style: { filter: 'sepia(0.3) saturate(1.4) brightness(1.05) contrast(1.05)' } },
    { name: 'TealOrange', style: { filter: 'hue-rotate(-20deg) contrast(1.1) saturate(1.3)' } },
    { name: 'Crisp', style: { filter: 'contrast(1.2) saturate(1.1) brightness(1.05)' } },
    { name: 'Pastel', style: { filter: 'brightness(1.1) saturate(0.8) contrast(0.9)' } },
    { name: 'Clean', style: { filter: 'brightness(1.05) contrast(1.05) saturate(1.0)' } },
    { name: 'Pink', style: { filter: 'sepia(0.2) hue-rotate(310deg) saturate(1.2)' } },
    { name: 'Night', style: { filter: 'brightness(0.7) contrast(1.2) saturate(1.1) hue-rotate(-10deg)' } },
    { name: 'Sharpen', style: { filter: 'contrast(1.35) brightness(1.0)' } }, // Simulating sharpen roughly
];
